name       : wkhtmltopdf
version    : 0.12.5
release    : 1
source     :
    - git|https://github.com/wkhtmltopdf/wkhtmltopdf.git : 0.12.5
license    : LGPL-3.0-or-later
component  : office
summary    : HTML to PDF converter
description: |
    wkhtmltopdf and wkhtmltoimage are open source command line tools to render HTML into PDF and various image formats using the Qt WebKit rendering engine.
    These run entirely "headless" and do not require a display or display service.
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
setup      : |
    %qmake wkhtmltopdf.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
